return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "typescript",
        "vim",
        "yaml",
        "c",
        "cmake",
        "cpp",
        "git_rebase",
        "go",
        "gomod",
        "gosum",
        "llvm",
        "ninja",
        "rust",
        "scala",
        "thrift",
        "dockerfile",
        "sql",
      },
    },
  },
}
